---

- name: 開発でよく使うパッケージを入れる
  become: yes
  apt:
    name:
      - tree
      - git
      - tig
      - vim
      - make
      - tmux
      - direnv
      - bash-completion
      - unzip
      - jq
      - wget
    update_cache: yes
    cache_valid_time: 3600
